"""Generate the evaluation report artefacts for the project submission.

Produces, under ``docs/``:
  * ``docs/figures/confusion_stage1.png``   Stage 1 confusion matrix
  * ``docs/figures/confusion_stage2.png``   Stage 2 confusion matrix
  * ``docs/figures/confusion_cascade.png``  3-way cascade confusion matrix
  * ``docs/figures/perplexity_hist.png``    GPT-2 perplexity: human vs AI
  * ``docs/results.md``                     metrics tables (pasted into REPORT.md)

Run after training:
    python -m aitext.report --sample 1500 --ppl-sample 300
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from sklearn.metrics import (  # noqa: E402
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
)

from .detector import Detector  # noqa: E402
from .paths import ROOT, STAGE1_CSV, STAGE2_CSV  # noqa: E402
from .preprocess import normalize  # noqa: E402

FIG_DIR = ROOT / "docs" / "figures"
RESULTS_MD = ROOT / "docs" / "results.md"


def _holdout(csv_path: Path, sample: int, seed: int) -> pd.DataFrame:
    test_path = csv_path.with_name(csv_path.stem + "_test.csv")
    df = pd.read_csv(test_path if test_path.exists() else csv_path)
    df = df.dropna(subset=["text", "label"])
    df = df[df["text"].str.split().str.len() >= 10]
    return df.sample(min(sample, len(df)), random_state=seed).reset_index(drop=True)


def _stage_eval(det: Detector, stage, df: pd.DataFrame):
    y = (df["label"].str.lower() == "ai").astype(int).to_numpy()
    p = np.array([det._predict(stage, normalize(t))[0] for t in df["text"]])  # noqa: SLF001
    return y, p


def _save_cm(cm, labels, title, path):
    disp = ConfusionMatrixDisplay(cm, display_labels=labels)
    fig, ax = plt.subplots(figsize=(4.5, 4))
    disp.plot(ax=ax, cmap="Blues", colorbar=False, values_format="d")
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)
    print(f"  wrote {path.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Build evaluation report artefacts")
    ap.add_argument("--sample", type=int, default=1500)
    ap.add_argument("--ppl-sample", type=int, default=300)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    FIG_DIR.mkdir(parents=True, exist_ok=True)
    det = Detector()
    if not det.ready:
        raise SystemExit("Models not trained. Run: python -m aitext.train")

    s1 = _holdout(STAGE1_CSV, args.sample, args.seed)
    s2 = _holdout(STAGE2_CSV, args.sample, args.seed)
    md: list[str] = ["<!-- generated by `python -m aitext.report` -->",
                     "## Held-out evaluation\n"]

    # ---- Stage 1 / Stage 2 in isolation ----
    for tag, stage, df in [("Stage 1 — raw AI vs human", det._stage1, s1),  # noqa: SLF001
                           ("Stage 2 — humanized AI vs human", det._stage2, s2)]:  # noqa: SLF001
        y, p = _stage_eval(det, stage, df)
        pred = (p >= 0.5).astype(int)
        acc, auc = accuracy_score(y, pred), roc_auc_score(y, p)
        rep = classification_report(y, pred, target_names=["human", "ai"],
                                    digits=3)
        print(f"\n=== {tag} ===\n{rep}\nacc={acc:.3f} auc={auc:.3f}")
        md += [f"### {tag}", "",
               f"- Accuracy **{acc:.1%}**, ROC-AUC **{auc:.3f}** "
               f"(n={len(y)})", "", "```", rep, "```", ""]
        slug = "stage1" if "Stage 1" in tag else "stage2"
        _save_cm(confusion_matrix(y, pred), ["human", "ai"],
                 tag.split(" — ")[0], FIG_DIR / f"confusion_{slug}.png")

    # ---- 3-way cascade ----
    labels = ["human", "raw-ai", "humanized-ai"]
    gold, pred = [], []
    for t, lab in zip(s1["text"], s1["label"].str.lower()):
        gold.append("raw-ai" if lab == "ai" else "human")
        lb, st = det.classify_cascade(t)
        pred.append("human" if lb != "AI"
                    else ("humanized-ai" if st == "stage2" else "raw-ai"))
    for t, lab in zip(s2["text"], s2["label"].str.lower()):
        if lab != "ai":
            continue
        gold.append("humanized-ai")
        lb, st = det.classify_cascade(t)
        pred.append("human" if lb != "AI"
                    else ("humanized-ai" if st == "stage2" else "raw-ai"))

    cm = confusion_matrix(gold, pred, labels=labels)
    acc = accuracy_score(gold, pred)
    rep = classification_report(gold, pred, labels=labels, digits=3,
                                zero_division=0)
    ai_catch = (cm[2, 1] + cm[2, 2]) / cm[2].sum()
    print(f"\n=== 3-way cascade ===\n{rep}\nacc={acc:.3f} "
          f"humanized-caught-as-AI={ai_catch:.3f}")
    md += ["### End-to-end cascade (3-way)", "",
           f"- Accuracy **{acc:.1%}**", "",
           f"- Humanized-AI still flagged as AI-generated: **{ai_catch:.1%}**",
           "", "```", rep, "```", "",
           "![cascade confusion](figures/confusion_cascade.png)", ""]
    _save_cm(cm, labels, "3-way cascade", FIG_DIR / "confusion_cascade.png")

    # ---- perplexity distribution ----
    try:
        from .perplexity import _load_model, _text_perplexity  # noqa: PLC2701
        tok, model, device = _load_model()
        sub = (s1.groupby("label", group_keys=False)
                 .apply(lambda g: g.sample(min(len(g), args.ppl_sample // 2),
                                           random_state=args.seed)))
        vals = {"human": [], "ai": []}
        for t, lab in zip(sub["text"], sub["label"].str.lower()):
            v = _text_perplexity(t, tok, model, device)
            if v and np.isfinite(v):
                vals[lab].append(min(v, 300))
        fig, ax = plt.subplots(figsize=(6, 3.5))
        ax.hist(vals["human"], bins=40, alpha=0.6, label="human", color="#1e8449")
        ax.hist(vals["ai"], bins=40, alpha=0.6, label="AI", color="#c0392b")
        ax.set_xlabel("GPT-2 perplexity (capped at 300)")
        ax.set_ylabel("count")
        ax.set_title("Perplexity: human vs AI")
        ax.legend()
        fig.tight_layout()
        fig.savefig(FIG_DIR / "perplexity_hist.png", dpi=130)
        plt.close(fig)
        print(f"  wrote {(FIG_DIR / 'perplexity_hist.png').relative_to(ROOT)}")
        md += ["### GPT-2 perplexity distribution", "",
               "![perplexity](figures/perplexity_hist.png)", "",
               f"Median perplexity — human {np.median(vals['human']):.1f}, "
               f"AI {np.median(vals['ai']):.1f}.", ""]
    except Exception as exc:  # noqa: BLE001
        print(f"[report] perplexity histogram skipped: {exc}")

    RESULTS_MD.write_text("\n".join(md), encoding="utf-8")
    print(f"\nwrote {RESULTS_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
